-- 1.Create the Database
CREATE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
SELECT CURRENT_DATABASE();

-- 2.Create the Warehouse
CREATE WAREHOUSE SUPPLY_CHAIN_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SUPPLY_CHAIN_WH;

-- 3.Create Schemas in Database
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA ANALYTICS;

SHOW SCHEMAS;
SHOW WAREHOUSES;

-- 4.Creating a file format and stage
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA RAW;
CREATE OR REPLACE STAGE DATA_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES IN SCHEMA RAW;

USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA RAW;

-- Create a File Format
CREATE OR REPLACE FILE FORMAT SUPPLY_CHAIN_ANALYTICS.RAW.CSV_LOAD_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ENCODING = 'ISO-8859-1'; -- Kaggle dataset often contains non-UTF8 characters

-- Create the RAW table with clean column identifiers
CREATE OR REPLACE TABLE SUPPLY_CHAIN_ANALYTICS.RAW.DATACO_RAW (
    TYPE VARCHAR,
    DAYS_FOR_SHIPPING_REAL VARCHAR,
    DAYS_FOR_SHIPMENT_SCHEDULED VARCHAR,
    BENEFIT_PER_ORDER VARCHAR,
    SALES_PER_CUSTOMER VARCHAR,
    DELIVERY_STATUS VARCHAR,
    LATE_DELIVERY_RISK VARCHAR,
    CATEGORY_ID VARCHAR,
    CATEGORY_NAME VARCHAR,
    CUSTOMER_CITY VARCHAR,
    CUSTOMER_COUNTRY VARCHAR,
    CUSTOMER_EMAIL VARCHAR,
    CUSTOMER_FNAME VARCHAR,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_LNAME VARCHAR,
    CUSTOMER_PASSWORD VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CUSTOMER_STATE VARCHAR,
    CUSTOMER_STREET VARCHAR,
    CUSTOMER_ZIPCODE VARCHAR,
    DEPARTMENT_ID VARCHAR,
    DEPARTMENT_NAME VARCHAR,
    LATITUDE VARCHAR,
    LONGITUDE VARCHAR,
    MARKET VARCHAR,
    ORDER_CITY VARCHAR,
    ORDER_COUNTRY VARCHAR,
    ORDER_CUSTOMER_ID VARCHAR,
    ORDER_DATE_DATEORDERS VARCHAR,
    ORDER_ID VARCHAR,
    ORDER_ITEM_CARDPROD_ID VARCHAR,
    ORDER_ITEM_DISCOUNT VARCHAR,
    ORDER_ITEM_DISCOUNT_RATE VARCHAR,
    ORDER_ITEM_ID VARCHAR,
    ORDER_ITEM_PRODUCT_PRICE VARCHAR,
    ORDER_ITEM_PROFIT_RATIO VARCHAR,
    ORDER_ITEM_QUANTITY VARCHAR,
    SALES VARCHAR,
    ORDER_ITEM_TOTAL VARCHAR,
    ORDER_PROFIT_PER_ORDER VARCHAR,
    ORDER_REGION VARCHAR,
    ORDER_STATE VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_ZIPCODE VARCHAR,
    PRODUCT_CARD_ID VARCHAR,
    PRODUCT_CATEGORY_ID VARCHAR,
    PRODUCT_DESCRIPTION VARCHAR,
    PRODUCT_IMAGE VARCHAR,
    PRODUCT_NAME VARCHAR,
    PRODUCT_PRICE VARCHAR,
    PRODUCT_STATUS VARCHAR,
    SHIPPING_DATE_DATEORDERS VARCHAR,
    SHIPPING_MODE VARCHAR
);

-- 5.Load raw transactional dataset from stage into Snowflake RAW table
COPY INTO SUPPLY_CHAIN_ANALYTICS.RAW.DATACO_RAW
FROM @SUPPLY_CHAIN_ANALYTICS.RAW.DATA_STAGE/DataCoSupplyChainDataset.csv
FILE_FORMAT = (
    FORMAT_NAME = 'SUPPLY_CHAIN_ANALYTICS.RAW.CSV_LOAD_FORMAT'
)
ON_ERROR = 'CONTINUE';

-- Verification: check row count loaded
SELECT COUNT(*) AS total_rows_loaded 
FROM SUPPLY_CHAIN_ANALYTICS.RAW.DATACO_RAW;

-- 6.Cleaning the data in STAGING Schema
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_SUPPLY_CHAIN_ORDERS AS
SELECT
    -- Identifiers
    TRY_CAST(ORDER_ID AS NUMBER) AS ORDER_ID,
    TRY_CAST(ORDER_ITEM_ID AS NUMBER) AS ORDER_ITEM_ID,
    TRY_CAST(CUSTOMER_ID AS NUMBER) AS CUSTOMER_ID,
    TRY_CAST(PRODUCT_CARD_ID AS NUMBER) AS PRODUCT_ID,
    TRY_CAST(DEPARTMENT_ID AS NUMBER) AS DEPARTMENT_ID,
    TRY_CAST(CATEGORY_ID AS NUMBER) AS CATEGORY_ID,

    -- Dates & Timestamps
    TRY_TO_TIMESTAMP(ORDER_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI') AS ORDER_TIMESTAMP,
    TRY_TO_DATE(ORDER_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI') AS ORDER_DATE,
    TRY_TO_TIMESTAMP(SHIPPING_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI') AS SHIPPING_TIMESTAMP,
    TRY_TO_DATE(SHIPPING_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI') AS SHIPPING_DATE,

    -- Shipping & Fulfillment
    TRY_CAST(DAYS_FOR_SHIPPING_REAL AS NUMBER) AS ACTUAL_SHIPPING_DAYS,
    TRY_CAST(DAYS_FOR_SHIPMENT_SCHEDULED AS NUMBER) AS SCHEDULED_SHIPPING_DAYS,
    DELIVERY_STATUS,
    TRY_CAST(LATE_DELIVERY_RISK AS NUMBER) = 1 AS IS_LATE_DELIVERY_RISK,
    SHIPPING_MODE,

    -- Financials & Sales Metrics
    TRY_CAST(ORDER_ITEM_QUANTITY AS NUMBER) AS ORDER_QUANTITY,
    TRY_CAST(ORDER_ITEM_PRODUCT_PRICE AS FLOAT) AS PRODUCT_PRICE,
    TRY_CAST(SALES AS FLOAT) AS GROSS_SALES,
    TRY_CAST(ORDER_ITEM_DISCOUNT AS FLOAT) AS DISCOUNT_AMOUNT,
    TRY_CAST(ORDER_ITEM_DISCOUNT_RATE AS FLOAT) AS DISCOUNT_RATE,
    TRY_CAST(ORDER_ITEM_TOTAL AS FLOAT) AS NET_SALES,
    TRY_CAST(ORDER_PROFIT_PER_ORDER AS FLOAT) AS PROFIT_PER_ORDER,
    TRY_CAST(ORDER_ITEM_PROFIT_RATIO AS FLOAT) AS PROFIT_RATIO,

    -- Customer Info
    CUSTOMER_FNAME AS CUSTOMER_FIRST_NAME,
    CUSTOMER_LNAME AS CUSTOMER_LAST_NAME,
    CUSTOMER_SEGMENT,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_COUNTRY,
    CUSTOMER_ZIPCODE,

    -- Geography & Order Details
    MARKET,
    ORDER_REGION,
    ORDER_COUNTRY,
    ORDER_STATE,
    ORDER_CITY,
    ORDER_STATUS,
    TYPE AS PAYMENT_TYPE,

    -- Product Details
    PRODUCT_NAME,
    CATEGORY_NAME,
    DEPARTMENT_NAME
FROM SUPPLY_CHAIN_ANALYTICS.RAW.DATACO_RAW;

-- 7.Move table from RAW to STAGING schema
USE DATABASE SUPPLY_CHAIN_ANALYTICS;

ALTER TABLE SUPPLY_CHAIN_ANALYTICS.RAW.STG_SUPPLY_CHAIN_ORDERS 
RENAME TO SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS;

SHOW TABLES IN SCHEMA SUPPLY_CHAIN_ANALYTICS.STAGING;

-- 8.Creating Fact and Dimension Tables
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA ANALYTICS;

-- 8.1.DIM_CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_FIRST_NAME,
    CUSTOMER_LAST_NAME,
    CUSTOMER_SEGMENT,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_COUNTRY,
    CUSTOMER_ZIPCODE
FROM SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS
WHERE CUSTOMER_ID IS NOT NULL;

-- 8.2.DIM_PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY_ID,
    CATEGORY_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    PRODUCT_PRICE
FROM SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS
WHERE PRODUCT_ID IS NOT NULL;

-- 8.3.DIM_ORDER 
CREATE OR REPLACE TABLE DIM_ORDER AS
SELECT DISTINCT
    ORDER_ID,
    PAYMENT_TYPE,
    ORDER_STATUS,
    MARKET,
    ORDER_REGION,
    ORDER_COUNTRY,
    ORDER_STATE,
    ORDER_CITY
FROM SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS
WHERE ORDER_ID IS NOT NULL;

-- 8.4.DIM_SHIPPING 
CREATE OR REPLACE TABLE DIM_SHIPPING AS
SELECT DISTINCT
    MD5(CONCAT(
        COALESCE(SHIPPING_MODE, ''),
        COALESCE(DELIVERY_STATUS, ''),
        COALESCE(CAST(IS_LATE_DELIVERY_RISK AS VARCHAR), '')
    )) AS SHIPPING_KEY,
    SHIPPING_MODE,
    DELIVERY_STATUS,
    IS_LATE_DELIVERY_RISK
FROM SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS;

-- 8.5.DIM_DATE 
CREATE OR REPLACE TABLE DIM_DATE AS
WITH DATE_RANGE AS (
    SELECT 
        DATEADD(DAY, SEQ4(), '2015-01-01'::DATE) AS DATE_VAL
    FROM TABLE(GENERATOR(ROWCOUNT => 365 * 6)) -- 6 years range (2015 - 2020)
)
SELECT
    DATE_VAL AS DATE_KEY,
    YEAR(DATE_VAL) AS YEAR,
    QUARTER(DATE_VAL) AS QUARTER,
    CONCAT('Q', QUARTER(DATE_VAL), ' ', YEAR(DATE_VAL)) AS QUARTER_YEAR,
    MONTH(DATE_VAL) AS MONTH_NUM,
    MONTHNAME(DATE_VAL) AS MONTH_NAME,
    CONCAT(MONTHNAME(DATE_VAL), ' ', YEAR(DATE_VAL)) AS MONTH_YEAR,
    WEEKOFYEAR(DATE_VAL) AS WEEK_OF_YEAR,
    DAYOFWEEK(DATE_VAL) AS DAY_OF_WEEK_NUM,
    DAYNAME(DATE_VAL) AS DAY_NAME,
    CASE WHEN DAYOFWEEK(DATE_VAL) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM DATE_RANGE
WHERE DATE_VAL <= '2020-12-31';

-- 8.6.FACT_SALES 
CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    s.ORDER_ITEM_ID,
    s.ORDER_ID,
    s.CUSTOMER_ID,
    s.PRODUCT_ID,
    
    -- Shipping Key
    MD5(CONCAT(
        COALESCE(s.SHIPPING_MODE, ''),
        COALESCE(s.DELIVERY_STATUS, ''),
        COALESCE(CAST(s.IS_LATE_DELIVERY_RISK AS VARCHAR), '')
    )) AS SHIPPING_KEY,
    
    -- Date Keys (links to DIM_DATE)
    s.ORDER_DATE AS ORDER_DATE_KEY,
    s.SHIPPING_DATE AS SHIPPING_DATE_KEY,
    
    -- Timestamps
    s.ORDER_TIMESTAMP,
    s.SHIPPING_TIMESTAMP,
    
    -- Operational Metrics
    s.ACTUAL_SHIPPING_DAYS,
    s.SCHEDULED_SHIPPING_DAYS,
    (s.ACTUAL_SHIPPING_DAYS - s.SCHEDULED_SHIPPING_DAYS) AS SHIPPING_DELAY_DAYS,
    
    -- Quantitative Financial Measures
    s.ORDER_QUANTITY,
    s.GROSS_SALES,
    s.DISCOUNT_AMOUNT,
    s.DISCOUNT_RATE,
    s.NET_SALES,
    s.PROFIT_PER_ORDER,
    s.PROFIT_RATIO
FROM SUPPLY_CHAIN_ANALYTICS.STAGING.STG_SUPPLY_CHAIN_ORDERS s;

-- 9.Check schema locations for existing tables
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, CREATED
FROM SUPPLY_CHAIN_ANALYTICS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('DIM_CUSTOMER', 'DIM_PRODUCT', 'DIM_ORDER', 'DIM_SHIPPING', 'DIM_DATE', 'FACT_SALES');

-- 10.Move tables from RAW to ANALYTICS schema
USE DATABASE SUPPLY_CHAIN_ANALYTICS;

ALTER TABLE RAW.DIM_CUSTOMER RENAME TO ANALYTICS.DIM_CUSTOMER;
ALTER TABLE RAW.DIM_PRODUCT RENAME TO ANALYTICS.DIM_PRODUCT;
ALTER TABLE RAW.DIM_ORDER RENAME TO ANALYTICS.DIM_ORDER;
ALTER TABLE RAW.DIM_SHIPPING RENAME TO ANALYTICS.DIM_SHIPPING;
ALTER TABLE RAW.DIM_DATE RENAME TO ANALYTICS.DIM_DATE;
ALTER TABLE RAW.FACT_SALES RENAME TO ANALYTICS.FACT_SALES;




